# base image
# Instructions copied from - https://hub.docker.com/_/python/
#FROM python:3-onbuild
FROM python

RUN mkdir -p /venya/web
COPY . /venya/web
WORKDIR /venya/web

# tell the port number the container should expose
EXPOSE 5000

# run the command
CMD ["python", "./appClient.py"]
